---
- name: upgrade all packages with yum
  become: yes
  yum: name=* state=latest

- name: Install epel
  become: yes
  yum: name=epel-release state=present

- name: Install common packages
  become: yes
  yum: name={{ item }}
  with_items: "{{ common_packages }}"
