---
- name: upgrade all packages with yum
  become: yes
  yum: name=* state=latest

- name: Install common packages with yum
  become: yes
  yum: name={{ item }} state=installed
  with_items: "{{ common_packages }}"
