---
- name: upgrade all packages with dnf
  sudo: yes
  dnf: name=* state=latest

- name: Install common packages with dnf
  sudo: yes
  dnf: name={{ item }} state=installed
  with_items: "{{ common_packages }}"
