---
- name: set distribution variables
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-family.yml"

- include: fedora.yml
  when: ansible_distribution == 'Fedora'

- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: redhat.yml
  when: ansible_distribution == 'RedHat'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: disable selinux
  become: yes
  selinux: state=disabled
  when: ansible_os_family == 'RedHat'

- name: Start the haveged service
  become: yes
  service: name=haveged enabled=yes state=started

- include: dotfiles.yml

- include: pipsi.yml
  become: no
  home: "{{ ansible_env.HOME }}"

- name: tty-less sudo
  become: yes
  lineinfile: dest=/etc/sudoers
              state=absent
              regexp='^Defaults(\s+)requiretty(\s*)$'
              validate='visudo -cf %s'

- name: Set server hostname
  become: yes
  hostname: name={{hostname}}
  when: hostname is defined
