---
# this is because some softlayer images ship with a bad apt install. If you
# apt-get update on the vm these problems get fixed but when using ansible
# it fails to get the apt lock.
- name: ensure apt folders
  become: yes
  file:
    state: directory
    name: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    recurse: no
  with_items:
    - /var/lib/apt/lists

- name: update apt packages
  become: yes
  apt: update_cache=yes cache_valid_time=300

- name: upgrade all packages with apt
  become: yes
  apt: upgrade=dist

- name: Install common packages
  become: yes
  apt: name={{ item }}
  with_items: "{{ common_packages }}"

- name: ack symlink
  become: yes
  file: state=link
        src=/usr/bin/ack-grep
        dest=/usr/bin/ack
  when: ansible_distribution_version == "14.04"

- name: Check if a reboot is required
  register: reboot_required
  stat: path=/var/run/reboot-required get_md5=no

- name: Restart server
  shell: sleep 2 && shutdown -r now "Reboot triggered by Ansible"
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_required.stat.exists == true
  become: yes

- name: Wait for server to reboot
  when: reboot_required.stat.exists == true
  become: no
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    delay: 10
    port: "{{ ansible_ssh_port | default(22) }}"
    timeout: 300
    state: started
