---
- name: update apt packages
  sudo: yes
  apt: update_cache=yes cache_valid_time=300

- name: upgrade all packages with apt
  sudo: yes
  apt: upgrade=dist

- name: Install common packages
  sudo: yes
  apt: name={{ item }}
  with_items: "{{ common_packages }}"

- name: ack symlink
  sudo: yes
  file: state=link
        src=/usr/bin/ack-grep
        dest=/usr/bin/ack

- name: Check if a reboot is required
  register: reboot_required
  stat: path=/var/run/reboot-required get_md5=no

- name: Restart server
  command: shutdown -r now "Reboot triggered by Ansible"
  async: 0
  poll: 0
  ignore_errors: true
  when: reboot_required.stat.exists == true
  sudo: yes

- name: Wait for server to reboot
  when: reboot_required.stat.exists == true
  sudo: no
  local_action: wait_for host={{ inventory_hostname }}
                         port={{ ansible_ssh_port | default(22) }}
                         delay=5
                         timeout=300
