---
- name: Install keystone SP
  hosts: keystone-sp
  sudo: yes
  pre_tasks:
    - name: add host entry for idp
      lineinfile:
        dest: /etc/hosts
        line: 129.41.140.58 keystone-idp
  roles:
      # - role: common
    - role: keystone
    - role: keystone-users
  vars:
    keystone_mappings:
      testshib:
        - local:
          - group:
              name: "testshib"
              domain:
                id: "default"
            user:
              name: "{0}"
          remote:
          - type: "eppn"
    keystone_shib_idps:
      - name: testshib
        mapping: testshib
        metadata_uri: http://www.testshib.org/metadata/testshib-providers.xml
      - name: keystoneidp
        mapping: testshib
        metadata_uri: http://keystone-idp:5000/v3/OS-FEDERATION/saml2/metadata
