- name: Install virtualbox packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualbox
    - virtualbox-dkms

- include: ensure-plugin.yml
  vagrant_plugin: vagrant-vbguest
