---
- name: install rdo release repos
  sudo: yes
  yum: pkg=http://rdo.fedorapeople.org/rdo-release.rpm state=installed

- name: install puppet packages
  sudo: yes
  yum: name={{ item }}
  with_items:
    - puppet
    - openstack-puppet-modules

- name: copy puppet hiera config
  sudo: yes
  template: src=hiera.j2 dest=/etc/puppet/hiera.yaml

- name: copy puppet modules
  sudo: yes
  synchronize: src=modules dest=/rdo recursive=yes set_remote_user=no

- name: Install IPA packages
  sudo: yes
  yum: name={{ item }}
  with_items:
    - ipa-client

# - name: IPA client install
#   sudo: yes
#   command: ipa-client-install --password {{ ipapassword }} --unattended
#   args:
#     creates: /etc/ipa/ca.crt

- name: Start certmonger
  sudo: yes
  service: name=certmonger enabled=yes state=started

- name: hiera directory
  sudo: yes
  file: state=directory path="{{ hiera_location }}"

- name: Setup hiera files
  sudo: yes
  copy: content="{{ item.value | to_nice_yaml }}" dest="{{ hiera_location }}/{{ item.key }}.yaml" force=yes
  with_dict: "{{ hierarchy }}"

- name: Install RDO
  sudo: yes
  command: puppet apply --modulepath /rdo/modules:/usr/share/openstack-puppet/modules/ -e "include rdoinstall"

- name: upload test image
  glance_image: login_username={{ admin_user }}
                login_password={{ admin_password }}
                login_tenant_name={{ admin_project_name }}
                name=cirros
                container_format=bare
                disk_format=qcow2
                state=present
                is_public=yes
                copy_from=http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
