---
- name: install rdo release repos
  sudo: yes
  yum: pkg=http://rdo.fedorapeople.org/rdo-release.rpm state=installed

- name: install puppet packages
  sudo: yes
  yum: name={{ item }}
  with_items:
    - puppet
    - openstack-puppet-modules

- name: copy puppet hiera config
  sudo: yes
  copy: src=hiera.yaml dest=/etc/puppet/hiera.yaml

- name: copy puppet modules
  sudo: yes
  synchronize: src=modules dest=/rdo recursive=yes set_remote_user=no

- name: Install RDO
  sudo: yes
  command: puppet apply --modulepath /rdo/modules:/usr/share/openstack-puppet/modules/ -e "include rdoinstall"
