# Example command line: ansible-playbook -i "fedora@10.16.18.218," devstack.yml

---
- name: set distribution variables
  include_vars: "{{ ansible_distribution | lower }}.yml"

- include: fedora.yml
  when: ansible_distribution == 'Fedora'

- include: centos.yml
  when: ansible_distribution == 'CentOS'

- include: redhat.yml
  when: ansible_distribution == 'RedHat'

- name: disable selinux
  sudo: yes
  selinux: state=disabled

- include: rngd.yml
- include: dotfiles.yml

- name: tty-less sudo
  sudo: yes
  lineinfile: dest=/etc/sudoers
              state=absent
              regexp='^Defaults(\s+)requiretty(\s*)$'
              validate='visudo -cf %s'

- name: Set server hostname
  sudo: yes
  hostname: name={{hostname}}
  when: hostname is defined
