---

- name: Check if fernet keys already exist
  stat:
    path: "{{ keystone_fernet_folder }}/0"
  register: _fernet_keys

- name: Create fernet keys
  command: >
    keystone-manage fernet_setup --keystone-user "{{ keystone_user }}"
                                 --keystone-group "{{ keystone_user }}"
  when: not _fernet_keys.stat.exists

- name: Rotate fernet keys for Keystone
  command: >
    keystone-manage fernet_rotate --keystone-user "{{ keystone_user }}"
                                  --keystone-group "{{ keystone_user }}"
  when: _fernet_keys.stat.exists
