- hosts: all
  gather_facts: False
  become: yes
  tasks:
    - name: install python 2 if it's not available (ubuntu)
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
